/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getAttribute(path: string, name: string): Promise<Buffer | null>
export declare function getAttributeSync(path: string, name: string): Buffer | null
export declare function setAttribute(path: string, name: string, value: Buffer | string): Promise<void>
export declare function setAttributeSync(path: string, name: string, value: Buffer | string): void
export declare function removeAttributeSync(path: string, name: string): void
export declare function removeAttribute(path: string, name: string): Promise<void>
export declare function listAttributes(path: string): Promise<Array<string>>
export declare function listAttributesSync(path: string): Array<string>
